---
title: Temporal Data in D3
layout: post
output: 
  md_document:
    preserve_yaml: true
---

_Static temporal data visualization in D3_

```{r, echo = FALSE}
library(knitr)
opts_knit$set(base_dir = "/", base.url = "/")
opts_chunk$set(
  warning = FALSE, 
  message = FALSE,
  fig.path = "stat679_notes/assets/week8-1/"
  )
```

1. These notes give the D3 analogs of some of the visualizations created in our
earlier notes on temporal visualization. For a pure static visualization, these
methods are not necessary — the R approach can give satisfactory results more
easily. However, if we ever want to customize the appearance or interactivity
beyond what is possible in the R packages we discussed, then these examples can
serve as a starting point.

1. Let’s begin with the basic line plot. We had given an example in these notes,
but we swept important details about d3’s path generators under the rug.

1. Remember that in these notes, we had manually generated paths using strings
like`M 20 20 L 5 5 L 10 10`. This means to start a path at pixel coordinates
(20, 20), move to the right and down by 5 units, and then move in the same
directions again by 10 units.

1. To map data to these types of coordinates, we can use an SVG path generator.
This is a function that converts an array of javascript objects to SVG path
strings like the one above. This is accomplished by using `d3.line()` and
supplying functions that give the `x` and `y` pixel coordinates given a single
object from the array. The `x` and `y` functions are usually light wrappers of
scales that map the raw data into pixel coordinates.

1. For example, to regenerate the lynx plot, we can use the code below.

1. If we want to draw a collection of paths, we can use an array of arrays. Each
element of the outer collection provides a path; each element within the inner
arrays gives one timepoint. For example, the code below generates the
electricity visualization from before.

1. At this point, it’s not hard to add in tooltips using mouseovers.

1. Path generators are just one example of a d3 function that maps raw data to
more complex visual marks. For example, to create a stacked time series
visualization, we can use `d3.stackArea()`

1. Using an alternative centering, the same area generator can be used to create
a d3 streamgraph.

1. Just to show how flexible d3 can be, let’s see how we can create two other
types of temporal visualizations from scratch: gantt charts and bump charts.

1. Gantt charts encode the start and end of discrete temporal events. They are
often used to organize projects. They can be generated by appending rectangles
at the right task (y) and time (x) coordinates.

1. Bump charts are line plots that show how ranks evolve over time. We can
create the smooth arcing lines using `.curve(d3.curveBumpX)`.

1. We can customize the color depending on whether the rank has increased or
decreased by storing the change in the data and encoding this using each path’s
stroke attribute.

1. You can see a full interactive version of this visualization at this link —
we’ll be discussing this in our next lecture. Notice the use of the voronoi
mouseover, like the one used in our previous notes. We’ll discuss some more
techniques for temporal interaction in the next set of notes.
