---
title: Hypothetical Outcomes
layout: post
output: 
  md_document:
    preserve_yaml: true
---

_Short description_

```{r, echo = FALSE}
library(knitr)
opts_knit$set(base_dir = "/", base.url = "/")
opts_chunk$set(
  warning = FALSE, 
  message = FALSE,
  fig.path = "stat679_notes/assets/week13-3/"
  )
```

1. From our previous discussions, we now have a rich set of techniques for
representing uncertainty for either discrete or continuous random values. But
often, we hope to support inferences for more complex objects, like curves,
compositions, or graphs. How can we visualize uncertainty in these more richly
structured objects?

1. For example, in linear regression, it’s possible to visualize the uncertainty
associated with the fit using a confidence band. The guarantee is that, across
many random samples from the same population, the line will usually fall
entirely within the band.

	[Show a confidence band]
	
1. Have you ever wondered why the band is shaped in the way that it is? The
curvature comes from the fact that there is uncertainty in both the intercept
and the slope for the fitted line. This is easy to understand by overlaying the
regression lines obtained from several versions of the same dataset. Formally,
we’ve applied the bootstrap to resample the original data, though we could have
just as well drawn from the posterior distribution of a fitted bayesian linear
regression.

1. We can generalize this idea to nonlinear fits. For example, below, we are
using multiple draws to represent the uncertainty of a smoothing spline
regression. One nice aspect of showing multiple realizations is that it shows
uncertainty in the “turns” of individual curves, which is not reflected in the
confidence bands alone.

1. When we show multiple outcomes overlaid like this, our attention tends to
focus on the area taken up by the multiple lines. In a true hypothetical outcome
plot, we animate each outcome one at a time. This draws attention to the
line-to-line uncertainty, rather than the area taken up by the ensemble.

1. A related idea was used in this visualization (), which both animated
individual events and displayed the full distribution in the background.

1. We can create a hypothetical outcome version of the plots above using the
`gganimate` package. This extends ggplot to allow transitions across subsets of
data.

1. A somewhat less standard, but more interactive, approach would be to use
dynamic linking. For example, in the dotplot to the right, each point is
associated with one hypothetical outcome. We can hover over individual outcomes
or brush the region below to highlight the corresponding fits in the original
display.

1. One aspect of hypothetical outcomes is that they represent uncertainty in the
data space, not the parameter space. For example, in the regression above, we
could have simply drawn error bars for the intercept and slope parameters of the
fit. This would be a representation of uncertainty in the parameter space. The
data space representation, however, is much more evocative, and preliminary
experimental evidence suggests that this leads to better inferences in practical
applications.

1. Though we have focused on hypothetical outcomes for relative simple settings,
the idea is applicable quite generally. For example, there has been research on
visualizing hypothetical outcomes on spatial and network data ([NetHOPS](https://arxiv.org/abs/2108.09870) and
[_Visualizing geospatial information uncertainty_](http://www.tandfonline.com/doi/abs/10.1559/1523040054738936)).

1. A final observation: hypothetical outcome plots can natural build up to
distributional visualizations. By layering the outcomes on top of one another,
we can see the distribution emerge over time. This was used effectively in this
visualization from the New York Times, for example.
