---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(brms)
library(ggdist)
theme_set(theme_bw())
```
```{r}
library(rethinking)
data(reedfrogs)
reedfrogs <- reedfrogs %>%
  mutate(tank = factor(row_number()))
```


```{r}
ggplot(reedfrogs) +
  geom_point(aes(propsurv, reorder(tank, propsurv), col = pred)) +
  facet_wrap(size ~ density, scales = "free_y")
```


```{r}
fit <- brm(
  data = reedfrogs, family = binomial,
  surv | trials(density) ~ 0 + factor(tank),
  prior(normal(0, 2))
)
```


```{r}
posterior <- as_draws_df(fit) %>%
  pivot_longer(matches("factortank"), names_to = "variable") %>%
  mutate(probability = inv_logit(value)) %>%
  mutate(tank = str_extract(variable, "[0-9]+")) %>%
  left_join(reedfrogs)

ggplot(posterior) +
  stat_pointinterval(aes(probability, reorder(tank, value), col = pred)) +
  facet_wrap(size ~ density, scales = "free_y")
```

```{r}
ggplot(posterior) +
  stat_pointinterval(aes(probability, reorder(tank, value), col = pred)) +
  geom_point(data = reedfrogs, aes(propsurv, tank), shape = 1) +
  facet_wrap(size ~ density, scales = "free_y")
  theme(axis.text.x = element_text(angle = 90))
```
```{r}
ggplot(posterior) +
  stat_slab(aes(probability, reorder(tank, value), col = pred, fill = pred), height = 2) +
  geom_point(data = reedfrogs, aes(propsurv, tank), shape = 1) +
  facet_wrap(size ~ density, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
y_sim <- posterior_predict(fit) %>%
  as_tibble() %>%
  set_names(1:ncol(.)) %>%
  mutate(.draw = row_number()) %>%
  pivot_longer(-.draw, names_to = "tank", values_to = "y_sim") %>%
  left_join(reedfrogs)
  
y_sim %>%
  filter(.draw < 10) %>%
  ggplot() +
  stat_dots(aes(y_sim, reorder(tank, y_sim), fill = pred, col = pred), dotsize = .5, binwidth = 1) +
  facet_wrap(size ~ density, scale = "free")

library(gganimate)
p <- y_sim %>%
  filter(.draw < 100) %>%
  ggplot() +
  geom_point(aes(y_sim, reorder(tank, y_sim), fill = pred, col = pred)) +
  facet_wrap(size ~ density, scale = "free") +
  transition_time(.draw)
anim_save("animation.gif", p)
```

